#pragma once

#include <QDialog>
#include <QString>
#include <QDir>

namespace Ui {
class QGitAddSubmoduleDialog;
}

class QGitAddSubmoduleDialog : public QDialog
{
    Q_OBJECT

public:
    explicit QGitAddSubmoduleDialog(const QDir &repoPath, QWidget *parent = nullptr);
    ~QGitAddSubmoduleDialog() override;

    QString url() const;
    QString path() const;
    QString branch() const;
    bool force() const;

private slots:
    void on_lineEdit_url_textChanged(const QString &text);
    void on_lineEdit_path_textChanged(const QString &text);
    void on_pushButton_browse_clicked();
    void updateButtons();

private:
    Ui::QGitAddSubmoduleDialog *ui;
    QDir m_repoPath;
    bool m_pathAutoGenerated = true;
};
