#include "qgitaddsubmoduledialog.h"
#include "ui_qgitaddsubmoduledialog.h"
#include <QPushButton>
#include <QFileDialog>
#include <QUrl>

QGitAddSubmoduleDialog::QGitAddSubmoduleDialog(const QDir &repoPath, QWidget *parent)
    : QDialog(parent)
    , ui(new Ui::QGitAddSubmoduleDialog)
    , m_repoPath(repoPath)
{
    ui->setupUi(this);

    connect(ui->lineEdit_url, &QLineEdit::textChanged, this, &QGitAddSubmoduleDialog::on_lineEdit_url_textChanged);
    connect(ui->lineEdit_path, &QLineEdit::textChanged, this, &QGitAddSubmoduleDialog::on_lineEdit_path_textChanged);
    connect(ui->pushButton_browse, &QPushButton::clicked, this, &QGitAddSubmoduleDialog::on_pushButton_browse_clicked);

    updateButtons();
}

QGitAddSubmoduleDialog::~QGitAddSubmoduleDialog()
{
    delete ui;
}

QString QGitAddSubmoduleDialog::url() const
{
    return ui->lineEdit_url->text().trimmed();
}

QString QGitAddSubmoduleDialog::path() const
{
    return ui->lineEdit_path->text().trimmed();
}

QString QGitAddSubmoduleDialog::branch() const
{
    return ui->lineEdit_branch->text().trimmed();
}

bool QGitAddSubmoduleDialog::force() const
{
    return ui->checkBox_force->isChecked();
}

void QGitAddSubmoduleDialog::on_lineEdit_url_textChanged(const QString &text)
{
    if (m_pathAutoGenerated || ui->lineEdit_path->text().trimmed().isEmpty()) {
        QString cleanUrl = text.trimmed();
        while (cleanUrl.endsWith('/') || cleanUrl.endsWith('\\')) {
            cleanUrl.chop(1);
        }
        if (cleanUrl.endsWith(QStringLiteral(".git"), Qt::CaseInsensitive)) {
            cleanUrl.chop(4);
        }

        int lastSlash = cleanUrl.lastIndexOf('/');
        int lastColon = cleanUrl.lastIndexOf(':');
        int splitPos = qMax(lastSlash, lastColon);
        if (splitPos >= 0 && splitPos < cleanUrl.length() - 1) {
            QString suggestedName = cleanUrl.mid(splitPos + 1);
            m_pathAutoGenerated = true;
            ui->lineEdit_path->setText(suggestedName);
        }
    }
    updateButtons();
}

void QGitAddSubmoduleDialog::on_lineEdit_path_textChanged(const QString &text)
{
    Q_UNUSED(text)
    if (!ui->lineEdit_url->hasFocus()) {
        m_pathAutoGenerated = false;
    }
    updateButtons();
}

void QGitAddSubmoduleDialog::on_pushButton_browse_clicked()
{
    QString dir = QFileDialog::getExistingDirectory(
        this,
        tr("Select Submodule Directory"),
        m_repoPath.absolutePath()
    );

    if (!dir.isEmpty()) {
        QString relPath = m_repoPath.relativeFilePath(dir);
        if (relPath.startsWith(QStringLiteral(".."))) {
            relPath = dir; // outside repository
        }
        m_pathAutoGenerated = false;
        ui->lineEdit_path->setText(relPath);
    }
}

void QGitAddSubmoduleDialog::updateButtons()
{
    QPushButton *okBtn = ui->buttonBox->button(QDialogButtonBox::Ok);
    if (okBtn) {
        okBtn->setEnabled(!url().isEmpty() && !path().isEmpty());
    }
}
